# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

version: 2

# https://goreleaser.com/customization/project/
# Name used prefix of the executable name created by the archive module
project_name: hello

# https://goreleaser.com/customization/hooks/
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

# https://goreleaser.com/cookbooks/builds-complex-envs/?h=builds
builds:
  - id: linux
    binary: hello
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    flags:
      - -trimpath
    ldflags:
      - "-X main.Version={{.Version}}"

  - id: osx
    binary: hello
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - "-X main.Version={{.Version}}"

  - id: windows
    binary: hello
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - "-X main.Version={{.Version}}"

# https://goreleaser.com/customization/archive/?h=archives
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

# https://goreleaser.com/customization/checksum/?h=checksum
checksum:
  name_template: "checksums.sha256"

# https://goreleaser.com/customization/changelog/?h=changelog
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# https://goreleaser.com/customization/homebrew/?h=homebrew
brews:
  - name: hello
    repository:
      owner: ch007m
      name: homebrew-helloworld
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: ch007m
      email: cmoulliard@redhat.com
    directory: Formula
    #homepage: https://cnoe.io/
    description: "Go HelloWorld example"
    #test: |
    #  system "idpbuilder version"

# https://goreleaser.com/customization/release/#release
release:
  target_commitish: '{{ .Commit }}'
  footer: >-
    ---
    
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
